# PyQt6 타입 스텁 파일
"""PyQt6 type stubs for better Pylance support"""

from typing import Any, Optional, List, Callable

class QObject:
    def __init__(self) -> None: ...

class QThread(QObject):
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def quit(self) -> None: ...
    def wait(self, msecs: int = ...) -> bool: ...
    def isRunning(self) -> bool: ...  # 메서드임을 명시
    def isFinished(self) -> bool: ...
    def run(self) -> None: ...

class pyqtSignal:
    def __init__(self, *args: Any) -> None: ...
    def emit(self, *args: Any) -> None: ...
    def connect(self, slot: Callable) -> None: ...
    def disconnect(self, slot: Optional[Callable] = None) -> None: ...

# QtCore 모듈
class QtCore:
    class QObject(QObject): ...
    class QThread(QThread): ...
    class pyqtSignal(pyqtSignal): ...

# QtWidgets 모듈  
class QApplication:
    def __init__(self, argv: List[str]) -> None: ...
    def exec(self) -> int: ...
    def quit(self) -> None: ...
    @staticmethod
    def instance() -> Optional['QApplication']: ...

class QWidget:
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def setAttribute(self, attribute: Any, on: bool = True) -> None: ...

class QMainWindow(QWidget):
    def setCentralWidget(self, widget: QWidget) -> None: ...

class QMessageBox:
    @staticmethod
    def critical(parent: Optional[QWidget], title: str, text: str) -> None: ...

class QtWidgets:
    class QApplication(QApplication): ...
    class QWidget(QWidget): ...
    class QMainWindow(QMainWindow): ...
    class QMessageBox(QMessageBox): ...